### ISSUE TITLE
Issue with units

### ISSUE THREAD

**Issue by YaoRenaudWoana** [5anthosh/fcal#2]
There is an issue with units when evaluating expressions:

**23 m / 23 m** should be evaluated to **1** not **1 Meters**

Same for multiplication:

**3 m * 3 m** should be evaluated to **9 Square Meters** not **9 Meters**

And so forth

**Comment by 5anthosh** [comment]
**23 m / 23 m** Should be evaluated **1  Meters**,  because dividend and divisor already associated with units

**Comment by YaoRenaudWoana** [comment]
If dividend and divisor have the same unit, the result should be without unit.

**Comment by 5anthosh** [comment]
I think you are right  ,  thanks for reporting this.
