### ISSUE TITLE
Control significant digits

### ISSUE THREAD

**Issue by lhagan** [5anthosh/fcal#6]
Currently, Fcal returns many digits of precision. For example, `100/3 = 33.333333333333333333`. This is excessive for my use -- rounding to a few significant digits would be better. Perhaps `evaluate` could take an optional argument that limits the digits of precision?

**Comment by 5anthosh** [comment]
types of results of evaluate will be under fcal.Type namespace. if the result is Type.Numeric,  then it will have `n` attribute which  is a Decimal type (attached repo)

[Decimal repo](https://github.com/MikeMcl/decimal.js)

**Comment by lhagan** [comment]
Thanks! I'm able to change the precision of the result like this:

```js
output = Fcal.eval("100/3");
output.n = output.n.toDP(2);
output.toString();
33.33
```

**Comment by 5anthosh** [comment]
👍🏽
